import type { OfferingDetail } from "./types";

export const mockOfferings: OfferingDetail[] = [
  {
    id: "gangdong-river-park",
    complexName: "강동 리버파크",
    slug: "gangdong-river-park",
    regionLabel: "서울 강동구",
    addressFull: "서울특별시 강동구 천호동 210-11",
    latitude: 37.5466,
    longitude: 127.1301,
    offeringType: "private_sale",
    saleCategory: "apt",
    currentStage: "special_supply_open",
    announcementName: "강동 리버파크 민간분양",
    announcementDate: "2026-03-03",
    moveInPlannedAt: "2028-06-01",
    dataCheckedAt: "2026-03-09T09:00:00+09:00",
    totalHouseholds: 820,
    developerName: "한강도시개발",
    builderName: "리버건설",
    supplySummary: "민간분양 / 신혼부부·생애최초·다자녀 특별공급",
    summaryText: "지금 특별공급 접수가 가능한 서울 동남권 핵심 입지 단지입니다.",
    minSalePrice: 680000000,
    maxSalePrice: 790000000,
    areaRangeLabel: "59㎡ - 84㎡",
    nextScheduleLabel: "특별공급 접수",
    nextScheduleAt: "2026-03-10",
    housingTypes: [
      {
        id: "gd-59a",
        typeName: "59A",
        exclusiveAreaM2: 59,
        supplyHouseholdsTotal: 210,
        supplyHouseholdsGeneral: 85,
        supplyHouseholdsSpecial: 125,
        salePriceMin: 680000000,
        salePriceMax: 695000000,
        contractDepositRate: 10,
        middlePaymentRate: 60,
        balanceRate: 30,
      },
      {
        id: "gd-74a",
        typeName: "74A",
        exclusiveAreaM2: 74,
        supplyHouseholdsTotal: 280,
        supplyHouseholdsGeneral: 100,
        supplyHouseholdsSpecial: 180,
        salePriceMin: 740000000,
        salePriceMax: 755000000,
        contractDepositRate: 10,
        middlePaymentRate: 60,
        balanceRate: 30,
      },
      {
        id: "gd-84a",
        typeName: "84A",
        exclusiveAreaM2: 84,
        supplyHouseholdsTotal: 330,
        supplyHouseholdsGeneral: 135,
        supplyHouseholdsSpecial: 195,
        salePriceMin: 785000000,
        salePriceMax: 790000000,
        contractDepositRate: 10,
        middlePaymentRate: 60,
        balanceRate: 30,
      },
    ],
    scheduleEvents: [
      {
        id: "gd-announcement",
        eventType: "announcement",
        startsAt: "2026-03-03",
        displayLabel: "모집공고 공개",
        status: "completed",
      },
      {
        id: "gd-special",
        eventType: "special_supply",
        startsAt: "2026-03-10",
        displayLabel: "특별공급 접수",
        status: "ongoing",
      },
      {
        id: "gd-priority1",
        eventType: "priority_1",
        startsAt: "2026-03-11",
        displayLabel: "1순위 접수",
        status: "upcoming",
      },
      {
        id: "gd-winner",
        eventType: "winner_announcement",
        startsAt: "2026-03-18",
        displayLabel: "당첨자 발표",
        status: "upcoming",
      },
      {
        id: "gd-contract",
        eventType: "contract",
        startsAt: "2026-04-05",
        endsAt: "2026-04-07",
        displayLabel: "계약",
        status: "upcoming",
      },
      {
        id: "gd-movein",
        eventType: "move_in",
        startsAt: "2028-06-01",
        displayLabel: "입주 예정",
        status: "upcoming",
      },
    ],
    supplyRules: [
      {
        id: "gd-general",
        supplyKind: "general",
        residentRegionRule: "서울 2년 이상 거주자 우선",
        homelessRequired: true,
        headOfHouseholdRequired: false,
        subscriptionAccountRequired: true,
        subscriptionMinPeriodMonths: 24,
        noteText: "1순위는 청약통장 가입 기간과 납입 횟수 확인 필요",
      },
      {
        id: "gd-newlywed",
        supplyKind: "special",
        specialSupplyType: "newlywed",
        residentRegionRule: "서울 및 수도권 거주자",
        homelessRequired: true,
        headOfHouseholdRequired: true,
        subscriptionAccountRequired: true,
        subscriptionMinPeriodMonths: 6,
        incomeRuleText: "도시근로자 월평균 소득 기준 충족 필요",
      },
      {
        id: "gd-first-time",
        supplyKind: "special",
        specialSupplyType: "first_time_buyer",
        residentRegionRule: "서울 및 수도권 거주자",
        homelessRequired: true,
        headOfHouseholdRequired: true,
        subscriptionAccountRequired: true,
        subscriptionMinPeriodMonths: 12,
      },
    ],
    regulationInfo: {
      priceCapApplied: false,
      resaleRestrictionMonths: 36,
      resaleRestrictionNote: "당첨자 발표일 기준 3년",
      residencyObligationMonths: 24,
      rewinRestrictionYears: 7,
      speculationZoneType: "adjustment_target",
      interimLoanAvailable: true,
      interimLoanNote: "중도금 대출 60% 범위 내 가능",
    },
    competitionRates: [
      {
        id: "gd-rate-84a",
        typeName: "84A",
        supplyKind: "general",
        recruitmentCount: 135,
        applicantCount: 1660,
        competitionRatio: 12.3,
        minWinningScore: 58,
        maxWinningScore: 72,
        avgWinningScore: 65,
      },
      {
        id: "gd-rate-newlywed",
        typeName: "74A",
        supplyKind: "special",
        specialSupplyType: "newlywed",
        recruitmentCount: 80,
        applicantCount: 520,
        competitionRatio: 6.5,
      },
    ],
    noticeHighlights: [
      "서울 2년 이상 거주자 우선공급 물량 포함",
      "85㎡ 이하 위주로 가점제 비중이 높음",
    ],
    locationHighlights: [
      "8호선 도보 8분",
      "초등학교 도보 5분",
      "대형마트 차량 10분",
    ],
  },
  {
    id: "hanam-lake-view",
    complexName: "하남 레이크뷰",
    slug: "hanam-lake-view",
    regionLabel: "경기 하남시",
    addressFull: "경기도 하남시 망월동 31-3",
    latitude: 37.5664,
    longitude: 127.1947,
    offeringType: "public_sale",
    saleCategory: "public_housing",
    currentStage: "announcement_open",
    announcementName: "하남 레이크뷰 공공분양",
    announcementDate: "2026-03-08",
    moveInPlannedAt: "2028-12-01",
    dataCheckedAt: "2026-03-09T09:00:00+09:00",
    totalHouseholds: 640,
    developerName: "하남도시공사",
    builderName: "시티하우징",
    supplySummary: "공공분양 / 일반공급·생애최초",
    summaryText: "공고가 공개된 공공분양으로 생애최초 수요에 유리한 구조입니다.",
    minSalePrice: 520000000,
    maxSalePrice: 590000000,
    areaRangeLabel: "59㎡ - 74㎡",
    nextScheduleLabel: "1순위 접수",
    nextScheduleAt: "2026-03-15",
    housingTypes: [
      {
        id: "hn-59a",
        typeName: "59A",
        exclusiveAreaM2: 59,
        supplyHouseholdsTotal: 360,
        supplyHouseholdsGeneral: 160,
        supplyHouseholdsSpecial: 200,
        salePriceMin: 520000000,
        salePriceMax: 540000000,
        contractDepositRate: 10,
        middlePaymentRate: 60,
        balanceRate: 30,
      },
      {
        id: "hn-74a",
        typeName: "74A",
        exclusiveAreaM2: 74,
        supplyHouseholdsTotal: 280,
        supplyHouseholdsGeneral: 140,
        supplyHouseholdsSpecial: 140,
        salePriceMin: 575000000,
        salePriceMax: 590000000,
        contractDepositRate: 10,
        middlePaymentRate: 60,
        balanceRate: 30,
      },
    ],
    scheduleEvents: [
      {
        id: "hn-announcement",
        eventType: "announcement",
        startsAt: "2026-03-08",
        displayLabel: "모집공고 공개",
        status: "ongoing",
      },
      {
        id: "hn-priority1",
        eventType: "priority_1",
        startsAt: "2026-03-15",
        displayLabel: "1순위 접수",
        status: "upcoming",
      },
      {
        id: "hn-winner",
        eventType: "winner_announcement",
        startsAt: "2026-03-23",
        displayLabel: "당첨자 발표",
        status: "upcoming",
      },
      {
        id: "hn-contract",
        eventType: "contract",
        startsAt: "2026-04-12",
        displayLabel: "계약",
        status: "upcoming",
      },
    ],
    supplyRules: [
      {
        id: "hn-general",
        supplyKind: "general",
        residentRegionRule: "하남시 및 수도권 거주자",
        homelessRequired: true,
        headOfHouseholdRequired: false,
        subscriptionAccountRequired: true,
        subscriptionMinPeriodMonths: 12,
      },
      {
        id: "hn-first-time",
        supplyKind: "special",
        specialSupplyType: "first_time_buyer",
        residentRegionRule: "수도권 거주자",
        homelessRequired: true,
        headOfHouseholdRequired: true,
        subscriptionAccountRequired: true,
        subscriptionMinPeriodMonths: 12,
        noteText: "생애최초 소득 및 자산 기준 추가 확인 필요",
      },
    ],
    regulationInfo: {
      priceCapApplied: true,
      resaleRestrictionMonths: 60,
      resaleRestrictionNote: "소유권 이전 등기 시까지 최대 5년",
      residencyObligationMonths: 36,
      rewinRestrictionYears: 10,
      speculationZoneType: "speculation_overheated",
      interimLoanAvailable: true,
      interimLoanNote: "정책자금 연계 가능 여부 확인 필요",
    },
    competitionRates: [
      {
        id: "hn-rate-59a",
        typeName: "59A",
        supplyKind: "general",
        recruitmentCount: 160,
        applicantCount: 1280,
        competitionRatio: 8,
        minWinningScore: 52,
        maxWinningScore: 65,
        avgWinningScore: 58,
      },
    ],
    noticeHighlights: [
      "공공분양으로 분양가 상한제 적용",
      "생애최초 특별공급 물량 비중이 높음",
    ],
    locationHighlights: [
      "신도시 생활권",
      "수변공원 접근성 우수",
      "초등학교 예정부지 인접",
    ],
  },
  {
    id: "mapo-central-view",
    complexName: "마포 센트럴뷰",
    slug: "mapo-central-view",
    regionLabel: "서울 마포구",
    addressFull: "서울특별시 마포구 아현동 404-7",
    latitude: 37.5542,
    longitude: 126.9556,
    offeringType: "public_sale",
    saleCategory: "apt",
    currentStage: "planned",
    announcementName: "마포 센트럴뷰 사전안내",
    announcementDate: "2026-03-14",
    moveInPlannedAt: "2029-03-01",
    dataCheckedAt: "2026-03-09T09:00:00+09:00",
    totalHouseholds: 1200,
    developerName: "서울주택도시공사",
    builderName: "센트럴건설",
    supplySummary: "공공분양 / 분양 예정",
    summaryText: "공고 전 단계로 일정이 가까워 빠르게 추적할 필요가 있는 단지입니다.",
    minSalePrice: 0,
    maxSalePrice: 0,
    areaRangeLabel: "59㎡ - 84㎡",
    nextScheduleLabel: "모집공고 예정",
    nextScheduleAt: "2026-03-14",
    housingTypes: [
      {
        id: "mp-59a",
        typeName: "59A",
        exclusiveAreaM2: 59,
        supplyHouseholdsTotal: 420,
        supplyHouseholdsGeneral: 190,
        supplyHouseholdsSpecial: 230,
        salePriceMin: 0,
        salePriceMax: 0,
        contractDepositRate: 10,
        middlePaymentRate: 60,
        balanceRate: 30,
      },
    ],
    scheduleEvents: [
      {
        id: "mp-announcement",
        eventType: "announcement",
        startsAt: "2026-03-14",
        displayLabel: "모집공고 예정",
        status: "upcoming",
      },
      {
        id: "mp-priority1",
        eventType: "priority_1",
        startsAt: "2026-03-22",
        displayLabel: "1순위 접수 예정",
        status: "upcoming",
      },
    ],
    supplyRules: [
      {
        id: "mp-general",
        supplyKind: "general",
        residentRegionRule: "서울 거주자 우선",
        homelessRequired: true,
        headOfHouseholdRequired: false,
        subscriptionAccountRequired: true,
        subscriptionMinPeriodMonths: 24,
      },
    ],
    regulationInfo: {
      priceCapApplied: true,
      resaleRestrictionMonths: 60,
      resaleRestrictionNote: "소유권 이전 등기 시까지",
      residencyObligationMonths: 36,
      rewinRestrictionYears: 10,
      speculationZoneType: "adjustment_target",
      interimLoanAvailable: false,
      interimLoanNote: "중도금 대출 가능 여부 추후 공고 확인 필요",
    },
    competitionRates: [],
    noticeHighlights: [
      "아직 모집공고 전 단계",
      "서울 거주자 우선 배정 가능성이 큼",
    ],
    locationHighlights: [
      "2호선 도보권",
      "업무지구 접근성 우수",
      "생활 인프라 밀집",
    ],
  },
  {
    id: "songdo-the-first",
    complexName: "송도 더퍼스트",
    slug: "songdo-the-first",
    regionLabel: "인천 연수구",
    addressFull: "인천광역시 연수구 송도동 118-5",
    latitude: 37.3944,
    longitude: 126.6522,
    offeringType: "private_sale",
    saleCategory: "apt",
    currentStage: "winner_announced",
    announcementName: "송도 더퍼스트 민간분양",
    announcementDate: "2026-02-20",
    moveInPlannedAt: "2028-11-01",
    dataCheckedAt: "2026-03-09T09:00:00+09:00",
    totalHouseholds: 710,
    developerName: "송도자산개발",
    builderName: "더퍼스트건설",
    supplySummary: "민간분양 / 당첨자 발표 완료",
    summaryText: "접수는 종료되었고 당첨자 발표가 완료된 상태입니다.",
    minSalePrice: 610000000,
    maxSalePrice: 760000000,
    areaRangeLabel: "74㎡ - 101㎡",
    nextScheduleLabel: "계약 예정",
    nextScheduleAt: "2026-03-25",
    housingTypes: [
      {
        id: "sd-84a",
        typeName: "84A",
        exclusiveAreaM2: 84,
        supplyHouseholdsTotal: 320,
        supplyHouseholdsGeneral: 180,
        supplyHouseholdsSpecial: 140,
        salePriceMin: 710000000,
        salePriceMax: 760000000,
        contractDepositRate: 10,
        middlePaymentRate: 60,
        balanceRate: 30,
      },
    ],
    scheduleEvents: [
      {
        id: "sd-announcement",
        eventType: "announcement",
        startsAt: "2026-02-20",
        displayLabel: "모집공고 공개",
        status: "completed",
      },
      {
        id: "sd-priority1",
        eventType: "priority_1",
        startsAt: "2026-03-02",
        displayLabel: "1순위 접수",
        status: "completed",
      },
      {
        id: "sd-winner",
        eventType: "winner_announcement",
        startsAt: "2026-03-17",
        displayLabel: "당첨자 발표",
        status: "ongoing",
      },
      {
        id: "sd-contract",
        eventType: "contract",
        startsAt: "2026-03-25",
        displayLabel: "계약 예정",
        status: "upcoming",
      },
    ],
    supplyRules: [
      {
        id: "sd-general",
        supplyKind: "general",
        residentRegionRule: "인천 및 수도권 거주자",
        homelessRequired: true,
        headOfHouseholdRequired: false,
        subscriptionAccountRequired: true,
        subscriptionMinPeriodMonths: 24,
      },
    ],
    regulationInfo: {
      priceCapApplied: false,
      resaleRestrictionMonths: 12,
      resaleRestrictionNote: "당첨자 발표일 기준 1년",
      residencyObligationMonths: 0,
      rewinRestrictionYears: 7,
      speculationZoneType: "non_regulated",
      interimLoanAvailable: true,
      interimLoanNote: "민간 금융권 중도금 대출 상품 연계",
    },
    competitionRates: [
      {
        id: "sd-rate-84a",
        typeName: "84A",
        supplyKind: "general",
        recruitmentCount: 180,
        applicantCount: 950,
        competitionRatio: 5.3,
        minWinningScore: 49,
        maxWinningScore: 61,
        avgWinningScore: 54,
      },
    ],
    noticeHighlights: [
      "비규제 지역 민간분양",
      "계약 일정이 가장 가까운 단지",
    ],
    locationHighlights: [
      "국제업무단지 접근 용이",
      "대형 상업시설 인접",
      "광역교통 개선 기대",
    ],
  },
];
